spring.application.name=springmongodb
spring.data.mongodb.uri=mongodb://localhost:27017/todo-manage-api
logging.level.root=INFO
logging.level.com.mongodb.springmongodb=DEBUG
spring.output.ansi.enabled=ALWAYS
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
